sudo: required
os: osx
install:
  - brew update
  - brew install python || true
  - brew install brew-cask || true
  - brew cask install google-chrome || true
  - pip3 install selenium
script:
  - python src/automate.py
